version: '3.5'

services:
  postgres:
    container_name: postgres-fiap
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fiap
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  api:
    image: fiappos/api-blog-professores:latest
    container_name: api-blog
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - postgres
    environment:
      DATABASE_USER: user
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: fiap
      DATABASE_PASSWORD: 123456

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-react
    restart: always
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - api
      
networks:
  app-network: 

volumes:
  postgres:
