version: '3.5'

services:
  postgres:
    container_name: postgres-fiap
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      - app-network
    restart: unless-stopped

  api:
    image: fiappos/api-blog-professores:latest
    container_name: api-blog
    restart: always
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - app-network
    depends_on:
      - postgres
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-web
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - app-network
    depends_on:
      - api
      
networks:
  app-network: 

volumes:
  postgres:
